### ISSUE TITLE
Reference to non-existent field 'gpus'.

### ISSUE THREAD

**Issue by mjohn123** [vlfeat/matconvnet-fcn#17]
I was successfully build matconvnet with GPU. Then I tried to run fcnTrain.m and got error as

```
Reference to non-existent field 'gpus'.

Error in fcnTrain (line 95)
bopts.useGpu = numel(opts.train.gpus) > 0 ;
```

If I comment the line `bopts.useGpu = numel(opts.train.gpus) > 0 ;`, I got a new error as

```
Error using  ' 
Transpose on ND array is not defined. Use PERMUTE instead.

Error in vl_argparse (line 76)
    values = horzcat(values, struct2cell(args{ai})') ;

Error in cnn_train_dag (line 32)
opts = vl_argparse(opts, varargin) ;

Error in fcnTrain (line 98)
info = cnn_train_dag(net, imdb, getBatchWrapper(bopts), ...
```

I am using MATLAB 2015b in Window OS, newest matconvnet and matconvnet-fcn versions. Someone got the same error? How can I solve it.

Thanks everybody

**Comment by islamamirul** [comment]
Hi mjohn123, I'm also getting the same error even if I enable the GPU. Did you find any way to fix it?

**Comment by mjohn123** [comment]
Hello islamamirul. I did not find any solution. I am using MATLAB 2015b. I think it maybe work in order version. But I did not try. If you find any solution. Please let me know. Thanks in adavance

**Comment by wangpichao** [comment]
I also encountered  this problem. I am using Matlab 2014b/2015b/2013b  under Ubuntu 14.04/windows 10. I have tried three GPUs, one K40, one GT730, one GTX 970, but on all of which the same error happens. How to handle it? Thanks in advance.

**Comment by xuranzhao711** [comment]
Hi, I encountered the same problem. If I am right, there is something wrong with the fcntrain.m script but there is an easy fix.  
First search and every _trainOpts_ and replace them by _opts.train_. 
Then change line 23 _opts.train = struct([])_  to _opts.train = []_;
For me fixed the problem.

**Comment by mjohn123** [comment]
Thank xuranzhao711. It worked now. It is good solution

**Comment by islamamirul** [comment]
Thanks a lot xuranzhao711. It's working perfectly now.

**Comment by wangpichao** [comment]
Thanks xuranzhao711. It's working now.

**Comment by tianzq** [comment]
It works for me, thanks @xuranzhao711
