### ISSUE TITLE
fcnTrain Error using imread (line 349) File "dataoc11" does not exist.

### ISSUE THREAD

**Issue by brisker** [vlfeat/matconvnet-fcn#24]
I am trying to train the fcn model when I got this error, have you ever met this before?
Warning: Control Character '\S' is not valid. See 'doc sprintf' for control characters valid in the format string.

**Comment by hfarhidzadeh** [comment]
I am facing this problem. How did you solve it?
Thanks

**Comment by mjohn123** [comment]
Hi, I solved it by using the modification

```

  labelsPath = strrep(imdb.paths.classSegmentation, '\', '\\');
  labelsPath = sprintf(labelsPath, name) ;
```
