### ISSUE TITLE
why the fcnTrain.m running so slow?

### ISSUE THREAD

**Issue by brisker** [vlfeat/matconvnet-fcn#25]
Is it because the DriverVersion and the ToolkitVersion not matched? 
How to solve this problem? Please help me,thank you!
CUDADevice with properties:

```
                  Name: 'GeForce GTX TITAN X'
                 Index: 1
     ComputeCapability: '5.2'
        SupportsDouble: 1
         DriverVersion: 7.5000
        ToolkitVersion: 6.5000
    MaxThreadsPerBlock: 1024
      MaxShmemPerBlock: 49152
    MaxThreadBlockSize: [1024 1024 64]
           MaxGridSize: [2.1475e+09 65535 65535]
             SIMDWidth: 32
           TotalMemory: 1.2885e+10
       AvailableMemory: 1.2609e+10
   MultiprocessorCount: 24
          ClockRateKHz: 1076000
           ComputeMode: 'Default'
  GPUOverlapsTransfers: 1
KernelExecutionTimeout: 1
      CanMapHostMemory: 1
       DeviceSupported: 1
        DeviceSelected: 1
```

train: epoch 01:   1/565: 0.9 Hz accuracy: 0.677 0.048 0.032 objective: 3.044
train: epoch 01:   2/565: 1.0 Hz accuracy: 0.691 0.048 0.033 objective: 3.035
train: epoch 01:   3/565: 1.0 Hz accuracy: 0.698 0.048 0.033 objective: 2.994

**Comment by mjohn123** [comment]
Hello, I think that you did not active GPU mode. Find and change `opts.train.gpus = []` to `opts.train.gpus = 1` . It needs more than 5GB GPU

**Comment by brisker** [comment]
@mjohn123   I set the cudnn mode false and I got 5.5Hz , is it still  slow? Have you enable the cudnn?

**Comment by brisker** [comment]
@mjohn123 
In fcnTrain I haven't found opts.train.gpus = []
only like this:
% training options (SGD)
opts.train = struct([]) ;
[opts, varargin] = vl_argparse(opts, varargin) ;

trainOpts.batchSize = 20 ;

trainOpts.numSubBatches = 10 ;

trainOpts.continue = true ;
% trainOpts.gpus = [1,2,3,4] ;
% trainOpts.gpus = [1] ;
trainOpts.gpus = [2] ;
trainOpts.prefetch = true ;
trainOpts.expDir = opts.expDir ;
trainOpts.learningRate = 0.0001 \* ones(1,50) ;

trainOpts.numEpochs = numel(trainOpts.learningRate) ;

**Comment by brisker** [comment]
@mjohn123    "opts.train.gpus = 1" or "opts.train.gpus = [1]"  ??

**Comment by mjohn123** [comment]
Let read that issue and do it. It worked

https://github.com/vlfeat/matconvnet-fcn/issues/17
